### PR TITLE
Support for Zabbix 2.0

### PR DESCRIPTION
**Pull request by evtuhovich**
Zabbix 2.0 has API version 1.4 (instead of 1.3 for Zabbix 1.8)

I've added support for some methods for 1.4 API version.

### CODE REVIEW

**Comment by dhruvbansal** [comment]
Thanks for the patch!

I see that your code essentially does a version check before passing certain parameters.  My hope was to cut a new major/minor version of Rubix to support Zabbix 2.0 and abandon support for 1.8 from that version forward.  This would be a much larger change, requiring new models to wrap the new concept of Host Interface, and so on.

Does the current version-checking code you've got solve an immediate need for you?  Have you run the tests and do they pass?  If so, I'm happy to release this as a new version with an incremented patch number until full support for Zabbix 2.0.

**Comment by evtuhovich** [comment]
So, if you want to drop 1.8 support, i don't need this patch, because this is was only start of work.

Can i help you to migrate to Zabbix 2.0?

**Comment by dhruvbansal** [comment]
yes, i agree that this is only the start.  a good start though!

i have a private development branch of rubix that is....30% of the way to supporting zabbix 2.0.  my own timeline for release is before March 31st of this year, but i'd like to deliver sooner.

help would be great ;)  i will try and find some time this week to clean up what i've got so far and push it as a separate branch in this repo.  will close this issue at that time and start a new one where we can communicate about what's changing.

thanks!

**Comment by evtuhovich** [comment]
Hi again!

I want to start working on rubix for zabbix 2.0 as soon as possible, so i really need your branch to start.

**Pull request merged**
